Iter15
ZnNr/go-metrics-and-alerting pull request #16
Opened 2024-02-06 19:41 UTC by ZnNr

Gopsutil  add

2024-02-07 14:49 UTC, tmvrus requested changes

2024-02-07 14:49 UTC, tmvrus commented on cmd/agent/main.go
> +		os.Exit(1)
просто так выходить, ничего не написав пользователю, как-то нехорошо
должен же он понять в чем проблема

2024-02-07 14:49 UTC, tmvrus commented on cmd/server/main.go
> +		os.Exit(1)
та же история

2024-02-07 14:49 UTC, tmvrus commented on internal/agent/agent.go
> +				a.storage.GopsutilMetricStore()
почему нельзя было разместить  RuntimeMetricStore и GopsutilMetricStore рядом и обойтись одним циклом?

2024-02-07 14:49 UTC, tmvrus commented on internal/agent/agent.go
> +	return err
эта ошибка скорее всего всегда будет nil, поскольку заполняется она только в горутинах, и к моменту выхода из функции, горутины еще даже не успееет запуститься, не говоря уже о том, контекст не завершится

2024-02-07 14:49 UTC, tmvrus commented on internal/agent/agent.go
> +}
RateLimit тут не работает, он тут персональный на ф-ю которая вся, целиком работает синхронно (в ней нет вызова горутины), то есть какой бы лимит не был, отправка всегда будет в один поток. Что бы разбить отправку на несколько потоков и ограничить их количество, делать это нужно в том месте где выполняются исходящие запросы: func() sendMetrics цикл range, выполнять http-запросы в разных горутинах, а их колчество регулировать с RateLimit

2024-02-07 14:49 UTC, tmvrus commented on internal/agent/agent.go
> +}
можем это на 1-1 обсудить, если текстом я не смог

2024-02-11 09:59 UTC, ZnNr commented on internal/agent/agent.go
> +				a.storage.GopsutilMetricStore()
разместил RuntimeMetricStore и GopsutilMetricStore рядом в одном цикле

2024-02-11 10:00 UTC, ZnNr commented on cmd/agent/main.go
> +		os.Exit(1)
переделал на вывод сообщения об ошибке создания логера

2024-02-11 10:00 UTC, ZnNr commented on cmd/server/main.go
> +		os.Exit(1)
переделал на вывод сообщения об ошибке создания логера

2024-02-11 10:02 UTC, ZnNr commented on internal/agent/agent.go
> +}
сделал вызов горутины кейсе case numRequests <- struct{}{}:

2024-02-12 20:25 UTC, tmvrus approved these changes

2024-02-12 20:25 UTC, tmvrus commented on cmd/agent/main.go
> -		os.Exit(1)
os.Exit(1) можно было оставить, он сообщает вызывающей стороне, что программа завершилась с с ошибкой
https://en.wikipedia.org/wiki/Exit_status

2024-02-13 12:51 UTC, merged