Iter18
ZnNr/go-metrics-and-alerting pull request #19
Opened 2024-04-06 10:03 UTC by ZnNr

2024-04-09 19:53 UTC, tmvrus requested changes
<img width="764" alt="image" src="https://github.com/ZnNr/go-metrics-and-alerting/assets/554425/d978d76d-bc7f-4a9e-94e4-c94e3cef5c5f">

2024-04-09 19:53 UTC, tmvrus commented on cmd/server/main.go
> +//const pprofAddr string = ":8080"
закоменченный код в готовом проекте - дурной тон

2024-04-09 19:53 UTC, tmvrus commented on cmd/server/main.go
> +		os.Exit(1)
в этом месте произойдет завершение программы, до следующей строки управление не дойдет и пользователь не узнает что сломалось

2024-04-09 19:53 UTC, tmvrus commented on cmd/server/main.go
> +			os.Exit(1)
os.Exit -> log.Fatal одна строка вместо двух

2024-04-09 19:53 UTC, tmvrus commented on cmd/server/main.go
> +
закоменченый код

2024-04-09 19:53 UTC, tmvrus commented on internal/collector/collector_benchmarks_test.go
> +			assert.NoError(b, err)
а какой смысл проверять ошибку в бенчмарке? разве в этом его цель?

2024-04-09 19:53 UTC, tmvrus commented on internal/collector/collector_benchmarks_test.go
> +}
а какой смысл делать 1 вложенный бенчмарк?

2024-04-09 19:53 UTC, tmvrus commented on internal/storage/storage_test.go
> +	t.Run("runtime metrics store test", func(t *testing.T) {
какой смысл делать по одному вложенному тесту?

2024-04-10 07:05 UTC, ZnNr commented on cmd/server/main.go
> +			os.Exit(1)
сделал так  			log.SugarLogger.Fatal(err.Error(), "open db error")

2024-04-10 08:04 UTC, ZnNr commented on internal/collector/collector_benchmarks_test.go
> +			assert.NoError(b, err)
вынес проверку ошибки за пределы цикла

2024-04-10 08:39 UTC, ZnNr commented on internal/collector/collector_benchmarks_test.go
> +}
каждый вложенный бенчмарк фокусируется на тестировании отдельного метода Collector

2024-04-10 08:40 UTC, ZnNr commented on internal/storage/storage_test.go
> +	t.Run("runtime metrics store test", func(t *testing.T) {
каждый вложенный бенчмарк фокусируется на тестировании отдельного метода

2024-04-10 08:44 UTC, ZnNr commented on internal/collector/collector_benchmarks_test.go
> +}
добавил  тестирование бенчмарка в комплексном сценарии из двух условных методов  (грубо упрощенном)

2024-04-10 09:58 UTC, ZnNr commented on cmd/server/main.go
> +//const pprofAddr string = ":8080"
почистил

2024-04-10 09:58 UTC, ZnNr commented on cmd/server/main.go
> +		os.Exit(1)
исправил

2024-04-10 09:58 UTC, ZnNr commented on cmd/server/main.go
> +
почистил

2024-04-10 13:26 UTC, tmvrus commented on internal/storage/storage_test.go
> +	t.Run("runtime metrics store test", func(t *testing.T) {
Тогда зачем он вложенный?
```
// зачем делать так
func TestStorage_GopsutilMetricStore(t *testing.T) {
	t.Run("gopsutil metrics store test", func(t *testing.T) {
	// бенчмарк
	}
}
// если можно сделать так	
func TestStorage_GopsutilMetricStore(t *testing.T) {
	// бенчмарк
}

2024-04-10 13:27 UTC, tmvrus approved these changes

2024-04-15 10:36 UTC, ZnNr commented on internal/storage/storage_test.go
> +	t.Run("runtime metrics store test", func(t *testing.T) {
исправил, спасибо!

2024-04-15 10:49 UTC, merged