Iter25
ZnNr/go-metrics-and-alerting pull request #26
Opened 2024-05-19 09:21 UTC by ZnNr

2024-05-20 11:40 UTC, tmvrus requested changes

2024-05-20 11:40 UTC, tmvrus commented on internal/agent/agent.go
> +	collector2 "github.com/ZnNr/go-musthave-metrics.git/internal/agent/collector"
какое креотивное название

2024-05-20 11:40 UTC, tmvrus commented on internal/flags/flags.go
> +	defaultGrpcAddr string = "127.0.0.1:3200"
необязательно указывать  тип, язык сам выводит в таких простых случаях

2024-05-20 11:40 UTC, tmvrus commented on internal/server/grpc/grpc.go
> +		}, status.Error(1, err.Error())
а почему 1, а не 7 например?

2024-05-20 11:40 UTC, tmvrus commented on internal/server/router/router.go
> +	r.Use(handler.CheckSubnetHandler)
а какой смысл всегда передавать CheckSubnetHandler если trusted subnet может не быть?

2024-05-20 11:40 UTC, tmvrus commented on internal/server/handlers/handlers.go
> +			_, ipnet, _ := net.ParseCIDR(h.trustedSubnet) // Разбираем доверенную подсеть для сравнения.
а это можно сделать один раз при старте сервиса, а не парсить при каждом запросе

2024-05-20 11:40 UTC, tmvrus commented on internal/agent/agent.go
> +		SetHeader("X-Real-IP", "173.17.0.2")
а где гарантия что этот адрес имеет хоть какое-то отношение в агенту?

2024-05-24 18:58 UTC, ZnNr commented on internal/agent/agent.go
> +	collector2 "github.com/ZnNr/go-musthave-metrics.git/internal/agent/collector"
поправил

2024-05-24 18:58 UTC, ZnNr commented on internal/flags/flags.go
> +	defaultGrpcAddr string = "127.0.0.1:3200"
исправил

2024-05-24 19:04 UTC, ZnNr commented on internal/server/router/router.go
> +	r.Use(handler.CheckSubnetHandler)
добавил проверку 	if params.TrustedSubnet != "" {
		r.Use(handler.CheckSubnetHandler)
	}

2024-05-24 19:11 UTC, ZnNr commented on internal/server/handlers/handlers.go
> +			_, ipnet, _ := net.ParseCIDR(h.trustedSubnet) // Разбираем доверенную подсеть для сравнения.
сделал работу с проверкой доверенной подсети более эффективной, т.к. парсинг производится только один раз при запуске сервиса.

2024-05-25 09:07 UTC, ZnNr commented on internal/agent/agent.go
> +		SetHeader("X-Real-IP", "173.17.0.2")
исправил на RealIP

2024-05-25 09:29 UTC, ZnNr commented on internal/server/grpc/grpc.go
> +		}, status.Error(1, err.Error())
исправил

2024-05-27 06:49 UTC, tmvrus approved these changes

2024-05-27 06:55 UTC, merged